# Generated by Django 3.1.3 on 2020-11-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Product',
        ),
    ]
